Add timeout code to wait till the volume is provisioned on the node. (#75)
Refactor the code to handle the case of delayed volume scheduling.

diff --git a/k8s/lib/plugin/flexvolume/openebs-iscsi b/k8s/lib/plugin/flexvolume/openebs-iscsi
--- a/k8s/lib/plugin/flexvolume/openebs-iscsi
+++ b/k8s/lib/plugin/flexvolume/openebs-iscsi
@@ -21,12 +21,14 @@
 
 #Initialize the logs and specs directory, if not already created
 #TBD : Check if this can be moved into the init section
-
 OEBSDEBUG=false
 SPECS_DIR="/tmp/openebs/specs"
 OLOGS_DIR="/tmp/logs/openebs-iscsi"
-mkdir -p ${OLOGS_DIR}
-mkdir -p ${SPECS_DIR}
+CHECK_VOLUME="${OLOGS_DIR}/checkvolumeexists.json"
+CREATE_VOLUME="${OLOGS_DIR}/createvolume.json"
+DELETE_VOLUME="${OLOGS_DIR}/deletevolume.json"
+mkdir -p "${OLOGS_DIR}"
+mkdir -p "${SPECS_DIR}"
 
 usage() {
     err "Invalid usage. Usage: "
@@ -72,7 +74,7 @@ createvolumespec(){
     debug "createvolumespec for ${VOLUMENAME} of size ${VOLUMESIZE}"
     #Clear the previously created volume spec
     #TBD : Handle the case of multiple invocations
-    clearvolumespec ${VOLUMENAME}
+    $( clearvolumespec "${VOLUMENAME}" )
 
     echo -e "---\
 kind: PersistentVolumeClaim\n\
@@ -96,6 +98,48 @@ clearvolumespec(){
     sudo rm -rf "${SPECS_DIR}/openebs-${VOLUMENAME}-pvc.yaml"
 }
 
+check_volume_status(){
+    # check_volume_status method is used to check the status of the volume after it is created.
+    # If the status is pending, then it creates a timeout loop of around 100s, within which
+    # If the status changes to running, then the timeout period is terminated, or else 
+    # If it remains in pending state, after timeout period expires, control passes to the script. 
+    i=1
+    output=0
+        while [ "${i}" -lt 11 ]
+        do       
+            echo -e "Calling checkvolumeexists. Attempt ${i} of 10"
+            status=$(checkvolumeexists "${VOLUMENAME}" "${OPENEBS_API_URL}")
+            
+            # Pending State
+            if [[ "${status}" == 1 ]] ; then
+                #VSM in pending state
+                echo -e "VSM created, in pending state" >> "${OLOGS_DIR}/openebs-iscsi.log" 
+                output=1
+
+            # Complete(Running) State
+            elif [[ "${status}" == 2 ]]; then
+                # Volume created successfully
+                echo -e "VSM created successfully" >> "${OLOGS_DIR}/openebs-iscsi.log" 
+                clearvolumespec "${VOLUMENAME}"
+                output=2
+                break
+
+            # Volume Creation Error. Volume not created. ${status}=0 
+            else
+                echo -e "Error while creating VSM" >> "${OLOGS_DIR}/openebs-iscsi.log" 
+                output=0
+            fi
+            
+            if [ "${i}" == 10 ]; then
+               echo "Exceeded number of requests to maya server.." >> "${OLOGS_DIR}/openebs-iscsi.log" 
+            fi
+            
+            i=$((i+1))
+            sleep 10
+        done
+    echo $output
+}
+
 checkvolumeexists(){
     VOLUMENAME=$1      
     OPENEBS_API_URL=$2     
@@ -103,75 +147,69 @@ checkvolumeexists(){
     debug "checkvolumeexists ${VOLUMENAME} ${OPENEBS_API_URL}/volume/info/${VOLUMENAME}"
 
     # Get curl response as well as HTTP Code
-    response=$( curl --write-out %{http_code} --silent \
-                    --output /tmp/logs/openebs-iscsi/checkvolumeexists.json \
-                    "${OPENEBS_API_URL}/volume/info/${VOLUMENAME}" )
+    response=$( curl --write-out %{http_code} --silent --output ${CHECK_VOLUME} \
+    "${OPENEBS_API_URL}/volume/info/${VOLUMENAME}" )
+    status=$( jq -r '.Status.Reason' ${CHECK_VOLUME} )
 
     debug "checkvolumeexists - response code ${response} :" 
-    debug "checkvolumeexists - response $(cat /tmp/logs/openebs-iscsi/checkvolumeexists.json )" 
-
-    if [ "${response}" == 200 ] ; then
-        # Volume Exists
-        targetportal=$(jq -r '.annotations.targetportal' /tmp/logs/openebs-iscsi/checkvolumeexists.json)
-        iqn=$(jq -r '.annotations.iqn' /tmp/logs/openebs-iscsi/checkvolumeexists.json)
+    debug "checkvolumeexists - response $(cat ${CHECK_VOLUME} )" 
+    result=0
+    echo "Response in checkvolumeexists is ${response}" >> ${OLOGS_DIR}/openebs-iscsi.log
+        # Volume in Pending State
+    if [[ "${response}" == "200" ]] && [[ "${status}" == "pending" ]] ; then
+        targetportal=$(jq -r '.annotations.targetportal' ${CHECK_VOLUME})
+        iqn=$(jq -r '.annotations.iqn' ${CHECK_VOLUME})
         data="${targetportal}\n${iqn}"
-        echo -e "${data}" > /tmp/logs/openebs-iscsi/specs.txt
+        echo -e "${data}" > "/tmp/logs/openebs-iscsi/specs.txt"
+        debug "checkvolumeexists - extracted details $(cat $SPECS_DIR/specs.txt )" 
+        echo -e "checkvolumeexists: VSM is in Pending State." >> ${OLOGS_DIR}/openebs-iscsi.log
+        result=1
+
+        # Volume in Running State
+    elif [[ "${response}" == "200" ]] && [[ "${status}" == "running" ]] ; then
+        targetportal=$(jq -r '.annotations.targetportal' ${CHECK_VOLUME})
+        iqn=$(jq -r '.annotations.iqn' ${CHECK_VOLUME})
+        data="${targetportal}\n${iqn}"
+        echo -e "${data}" > "/tmp/logs/openebs-iscsi/specs.txt"
         debug "checkvolumeexists - extracted details $(cat /tmp/logs/openebs-iscsi/specs.txt )" 
-        echo 1
+        echo -e "checkvolumeexists: VSM is in Complete State." >> ${OLOGS_DIR}/openebs-iscsi.log
+        result=2
     else
         # Volume doesn't exist
-        echo 0
+        echo -e "checkvolumeexists: Volume Doesn't already exist" >> ${OLOGS_DIR}/openebs-iscsi.log
+        result=0
     fi
+    echo "${result}"
 }
 
 createvolume(){
     VOLUMENAME=$1
     OPENEBS_API_URL=$2
     VOLUMESIZE=$3
-
+    output=0
     # Check if volume already exists
+    echo -e "Calling checkvolumeexists from createvolume method" >> ${OLOGS_DIR}/openebs-iscsi.log
     status=$(checkvolumeexists "${VOLUMENAME}" "${OPENEBS_API_URL}")
-    if [ "${status}" -ne 0 ] ; then
-       # Volume already exists
-       exit 0
-    fi
     
     # if it doesn't exist
-    createvolumespec "${VOLUMENAME}" "${VOLUMESIZE}"
+    echo -e "Above createvolumespec" >> ${OLOGS_DIR}/openebs-iscsi.log
+    $(createvolumespec "${VOLUMENAME}" "${VOLUMESIZE}")
 
     # Get curl response as well as HTTP Code
-    response=$( curl --write-out %{http_code} --silent \
-                    --output /tmp/logs/openebs-iscsi/createvolume.json \
-                    --silent -k -H "Content-Type: application/yaml" \
-                    -XPOST -d "$(cat /tmp/openebs/specs/openebs-${VOLUMENAME}-pvc.yaml)" \
-                    "${OPENEBS_API_URL}/volumes/" )
+    $( curl --write-out %{http_code} --output ${CREATE_VOLUME} --silent \
+     --fail -k -H "Content-Type: application/yaml" -XPOST -d  \
+     "$(cat /tmp/openebs/specs/openebs-${VOLUMENAME}-pvc.yaml)" "${OPENEBS_API_URL}/volumes/" )
 
-    sleep 30 
-    # Wait for response from server
-    # until $(curl --output /tmp/logs/openebs-iscsi/createvolume.json --silent --fail -k -H "Content-Type: application/yaml" \
-    #        -XPOST -d "$(cat /tmp/openebs/specs/openebs-${VOLUMENAME}-pvc.yaml)" \
-    #       "${OPENEBS_API_URL}/volumes/"); do
-    #printf '.'
-    # sleep 5 
-    # done
-
-    status=$(checkvolumeexists "${VOLUMENAME}" "${OPENEBS_API_URL}")
-    if [ "${status}" == 0 ] ; then
-       # Error while creating volume
-       echo 0
-    else
-        # Volume created successfully
-        clearvolumespec "${VOLUMENAME}"
-        echo 1
-    fi
+    output=$( check_volume_status )
+    echo $output
 }
 
 deletevolume() {
     OPENEBS_API_URL=$1
     VOLUMENAME=$2
 
-    curl "${OPENEBS_API_URL}/volume/delete/${VOLUMENAME}" > /tmp/logs/openebs-iscsi/deletevolume.json 
-    response=$(jq -r '.Status.Reason' /tmp/logs/openebs-iscsi/deletevolume.json)
+    $( curl "${OPENEBS_API_URL}/volume/delete/${VOLUMENAME}" > ${DELETE_VOLUME}) 
+    response=$( jq -r '.Status.Reason' ${DELETE_VOLUME})
     if [ "${response}" == "complete" ] ; then
         # Volume Deleted.
         clearvolumespec "${VOLUMENAME}"
@@ -191,8 +229,6 @@ domount() {
         OEBSDEBUG=true
     fi
     debug "domount $1 $2"
-
-
     OPENEBS_API_URL=$(echo "$2" | jq -r '.openebsApiUrl')
     VOLUMENAME=$(echo "$2" | jq -r '.name')
     SIZE=$(echo "$2" | jq -r '.size')
@@ -208,12 +244,32 @@ domount() {
         debug "domount volume is already mounted"
         exit 0
     fi
-
+    echo -e "Calling checkvolumeexists from domount method" > ${OLOGS_DIR}/openebs-iscsi.log
     status=$(checkvolumeexists "${VOLUMENAME}" "${OPENEBS_API_URL}")
-    if [ "${status}" -eq 0 ] ; then
+    status_volume=0
+    if [ "${status}" == 0 ] ; then
         # Volume doesn't exist, create Volume
         debug "domount create a new volume at $OPENEBS_API_URL"
-        createvolume "${VOLUMENAME}" "$OPENEBS_API_URL" "${SIZE}"
+        status_volume=$( createvolume "${VOLUMENAME}" "$OPENEBS_API_URL" "${SIZE}" )
+        if [[ "${status_volume}" == 0 ]]; then
+            echo -e "domount: volume creation failed, status is $status." >> ${OLOGS_DIR}/openebs-iscsi.log
+            exit 0
+        elif [[ "${status_volume}" == 1 ]]; then
+            echo -e "domount: Volume In Pending State $status." >> ${OLOGS_DIR}/openebs-iscsi.log          
+            #statements
+        elif [[ "${status_volume}" == 2 ]]; then
+            echo -e "domount: Volume Created successfully $status." >> ${OLOGS_DIR}/openebs-iscsi.log
+        else
+            echo -e "domount: Unknown Error." >> ${OLOGS_DIR}/openebs-iscsi.log      
+        fi
+
+    # Volume already Created, but is in Pending State
+    elif [[ "${status}" -eq 1 ]]; then
+        echo -e "Creating a timeout loop" >> ${OLOGS_DIR}/openebs-iscsi.log
+        output=$( check_volume_status )
+    else
+        # Volume already created, and is in Success State
+        echo -e "domount: volume already created" >> ${OLOGS_DIR}/openebs-iscsi.log
     fi
 
     # Volume successfully created, get target portal and iqn values.
@@ -226,8 +282,8 @@ domount() {
         declare "var$i"=$t
         i=$((i+1))
     done
-    targetportal="${var0}";
-    iqn="${var1}";
+    targetportal="${var0}"
+    iqn="${var1}"
 
     #TBD  - Handle error checks for each of the commands
     debug "domount volume at $targetportal and $iqn"
@@ -236,11 +292,11 @@ domount() {
     devx=$(sudo iscsiadm -m session -P 3 |grep -i "Attached scsi disk" | awk '{print $4}')
     # The device can take a few more seconds to appear under /dev
     waiti=0
-    while devx==""; do
+    while [ "${devx}"=="" ]; do
         sleep 5
         devx=$(iscsiadm -m session -P 3 |grep -i "Attached scsi disk" | awk '{print $4}')
-        waiti=waiti+1
-        if waiti==5; then
+        waiti=$((waiti+1))
+        if [ "${waiti}" == 5 ]; then
                 break
         else
                 continue
@@ -248,9 +304,9 @@ domount() {
     done
 
     debug "domount - mounting iscsi device /dev/$devx as ${MNTPATH}" 
-    sudo mkdir -p ${MNTPATH}
-    debug $(sudo mkfs.ext4 -F /dev/$devx 2>&1)
-    sudo mount -t ext4 /dev/$devx ${MNTPATH}
+    sudo mkdir -p "${MNTPATH}"
+    debug $(sudo mkfs.ext4 -F "/dev/$devx" 2>&1)
+    sudo mount -t ext4 "/dev/$devx" "${MNTPATH}" 
 
     if [ $? -ne 0 ]; then
         2>&1
@@ -260,9 +316,9 @@ domount() {
     fi
     debug "domount - mounted iscsi device /dev/$devx as ${MNTPATH}" 
     log '{"status": "Success"}'
+    
     exit 0
 }
-
 unmount() {
     MNTPATH=$1
     if [ $(ismounted) -eq 0 ] ; then
@@ -270,9 +326,10 @@ unmount() {
       exit 0
     fi
 
-    umount ${MNTPATH} &> /dev/null
+    umount ${MNTPATH} &> "/dev/null"
     if [ $? -ne 0 ]; then
-      err "{ \"status\": \"Failed\", \"message\": \"Failed to unmount volume at ${MNTPATH}\"}"                exit 1
+      err "{ \"status\": \"Failed\", \"message\": \"Failed to unmount volume at ${MNTPATH}\"}"
+      exit 1
     fi
     log '{"status": "Success"}'
     exit 0
